### ISSUE TITLE
Is it possible to use a dictionary with more than 254 entries?

### ISSUE THREAD

**Issue by ghost** [macarie/compatto#5]
I think of using Compatto instead of smaz since it supports UNICODE and I am having Arabic as a language.
The thing is that, I want to accept English and Arabic and probably French in the future. If possible without adding anothing library to detect a language (then choose the appropriate dictionary), I want to have a big dictionary with all common words for these languages.

I don't know the internals of compatto so what do you think of a dictionary of say 600 keywords. 

thanks a lot !!

**Comment by macarie** [comment]
I'm sorry, but you can't use a dictionary that contains more than 254 _words_.

Sadly this is a limitation of the algorithm, but it's also its power: the compression is done using bytes (`2^8`, so `256` possible values). This means that:
- the range `[0, 253]` (inclusive) is directly mapped to the dictionary (e.g. `0` is mapped to [`' '`](https://github.com/macarie/compatto/blob/v2.1.4/dictionary.js#L2));
- `254` means that the next byte is a character that should be immediately decoded using [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder);
- `255` is followed by another byte, this pair of bytes indicates that the byte following `255` should be read as a number, `n`, and that the following `n` bytes should be decoded immediately using the TextDecoder mentioned above.

Maybe it'd be possible to change the algorithm and use 16 bits instead of 8, but then there would hardly be any compression, or to, somehow, support bigger dictionaries, but then it wouldn't be based on the smaz algorithm anymore.

I hope that this was a helpful explanation 😄

**Comment by ghost** [comment]
Sure I understood the down size mapping responsible for compression. Thank you for explanations. 

In terms of Arabic, do you think with a separate dictionary all will work as expected?

**Comment by ghost** [comment]
Also, can I require ('compatto')? Import is impossible in my project but I will retry tomorrow.

**Comment by macarie** [comment]
> In terms of Arabic, do you think with a separate dictionary all will work as expected?

I don't know the language, but I've tried compatto with emojis and it works, so it should work with Arabic as well.

> Also, can I require ('compatto')? Import is impossible in my project but I will retry tomorrow.

Nope, I can release a new version with support for `require` tho.

**Comment by ghost** [comment]
Hopefully. Thank you so much.

**Comment by macarie** [comment]
@bacloud14 I've released `v2.1.5`: now it should work with `require` as well.
Let me know if something's not working 👍🏼

_Note_: with Node 12 you may have to import the dictionary using `compatto/cjs/dictionary.cjs`.

**Comment by ghost** [comment]
I cannot believe you made it fast after my request. I really appreciate it 🙂 
I will use it later and tell you how it goes with Arabic. Thanks a lot

**Comment by ghost** [comment]
My first test is like:
```

var {compatto, DecompressError} = require('compatto')
var english = require("./node_modules/compatto/cjs/dictionary.cjs").dictionary
console.log(english.length) // outputs 254
console.log( Array.isArray(english)) //outputs true
const { compress, decompress } = compatto({ english })
const compressedString = compress("this is a string")
const decompressedString = decompress(compressedString)

console.log(decompressedString)
```

I am having 

`TypeError: The `dictionary` option must be an array with at most 254 elements. It is `undefined`.`

thanks a lot !

**Comment by ghost** [comment]
`compatto({ dictionary: english })` is the way.

**Comment by ghost** [comment]
in regards of this issue, it works fine with Arabic ! 
https://raw.githubusercontent.com/oprogramador/most-common-words-by-language/master/src/resources/arabic.txt

var fs = require("fs");
var text = fs.readFileSync("./arabic.txt").toString('utf-8');
var arabic = text.split("\n").slice(0, 245)

```
var { compatto, DecompressError } = require('compatto')
var english = require("./node_modules/compatto/cjs/dictionary.cjs").dictionary
const { compress, decompress } = compatto({ dictionary: arabic })
const compressedString = compress("يعمل الشمندر على إزالة السموم من الدم، ويساعد البرتقال في الحفاظ على البشرة والجسم، إذن ماذا يحدث عند مزج عصير الشمندر والبرتقال معًا؟ تعرف في هذا المقال على فوائد عصير الشمندر والبرتقال. ")
console.log(compressedString)
const decompressedString = decompress(compressedString)

fs.writeFile('text.txt', decompressedString, function (err) {
    if (err) return console.log(err);
  });
```

Thanks a lot !
